# Generated by Django 2.2.3 on 2020-03-30 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneyfishapp', '0002_auto_20200328_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='user',
        ),
        migrations.RemoveField(
            model_name='outgoing',
            name='user',
        ),
        migrations.AlterField(
            model_name='income',
            name='insource',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='invalue',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
