# Generated by Django 2.2.3 on 2020-03-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyfishapp', '0004_auto_20200330_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debts',
            name='dvalue',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='lvalue',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='outsource',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='outvalue',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
