# Generated by Django 2.2.3 on 2020-03-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneyfishapp', '0005_auto_20200330_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='insource',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='outgoing',
            name='outsource',
            field=models.CharField(max_length=128),
        ),
    ]
